### PR TITLE
Feat: implement react router dom

### PR DESCRIPTION
**Pull request by thezeeshann**
issue #1

### CODE REVIEW

**Comment by sahilsingh7735** [comment]
@thezeeshann have you taken pull before raising PR..

**Comment by thezeeshann** [comment]
@sahilsingh7735 I am a new branch emerging from the master branch.

**Comment by sahilsingh7735** [comment]
Can you tell me what is your branch name?

**Comment by thezeeshann** [comment]
@sahilsingh7735 branch name feature/react-router-dom

**Comment by sahilsingh7735** [comment]
Take the latest pull from Master there are some changes in the code and publish it on my repo.

**Comment by thezeeshann** [comment]
@sahilsingh7735 bro check I published the latest code

**Pull request merged**
